sonar.projectKey=KaustubhRanjan_SIT753_7.3HD
sonar.organization=kaustubhranjan
sonar.host.url=https://sonarcloud.io
sonar.token=${SONAR_TOKEN}
sonar.sources=.
sonar.exclusions=node_modules/**,.scannerwork/**
sonar.projectName=SIT753 7.3HD DevOps Pipeline
sonar.sourceEncoding=UTF-8